//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Fund.DBFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NumberOfRoom { get; set; }
        public Nullable<int> IdLocationInBuilding { get; set; }
        public string Appointment { get; set; }
        public Nullable<int> IdRoomType { get; set; }
        public Nullable<double> RoomLength { get; set; }
        public Nullable<double> RoomWidth { get; set; }
        public Nullable<int> IdUniversityDivision { get; set; }
    
        public virtual LocationInBuilding LocationInBuilding { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual UniversityDivision UniversityDivision { get; set; }
    }
}
